version: '3'

services:
  db:
    build:
      context: ./docker/db/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: mt
      MYSQL_USER: mt
      MYSQL_PASSWORD: password
