version: '3'

services:
  perl:
    build:
      context: ./docker/perl
    volumes:
      - type: bind
        source: ./example
        target: /usr/local/apache2/vhosts/localhost
  httpd:
    image: httpd:2.4.54-alpine3.17
    volumes:
      - type: bind
        source: ./docker/httpd/httpd.conf
        target: /usr/local/apache2/conf/httpd.conf
      - type: bind
        source: ./docker/httpd/httpd-vhosts.conf
        target: /usr/local/apache2/conf/extra/httpd-vhosts.conf
      - type: bind
        source: ./docker/httpd/httpd-ignore-files.conf
        target: /usr/local/apache2/conf/extra/httpd-ignore-files.conf
      - type: bind
        source: ./example
        target: /usr/local/apache2/vhosts/localhost
    ports:
      - "80:80"
  php:
    build:
      context: ./docker/php
    volumes:
      - type: bind
        source: ./example
        target: /usr/local/apache2/vhosts/localhost
